export const EVENT_CATEGORY_GROUPS = [
  {
    name: 'Music',
    items: [
      'Live Band',
      'Afrobeats',
      'Hip-Hop',
      'Jazz',
      'Classical',
      'Gospel',
      'Electronic',
      'Open Mic',
      'Karaoke',
      'DJ Set',
    ],
  },
  {
    name: 'Business',
    items: [
      'Startup',
      'Networking',
      'Leadership',
      'Marketing',
      'Sales',
      'Finance',
      'Product',
      'Real Estate',
      'Small Business',
      'Career Fair',
    ],
  },
  {
    name: 'Technology',
    items: [
      'AI',
      'Web Development',
      'Mobile Development',
      'Cloud',
      'Cybersecurity',
      'Data Science',
      'DevOps',
      'Product Design',
      'No-Code',
      'Blockchain',
    ],
  },
  {
    name: 'Arts & Culture',
    items: [
      'Exhibition',
      'Painting',
      'Photography',
      'Film',
      'Poetry',
      'Literature',
      'Museum Tour',
      'Cultural Festival',
      'Craft Fair',
      'Theatre',
    ],
  },
  {
    name: 'Food & Drink',
    items: [
      'Tasting',
      'Brunch',
      'Dinner',
      'Street Food',
      'Cooking Class',
      'Wine',
      'Cocktail',
      'Coffee',
      'BBQ',
      'Food Festival',
    ],
  },
  {
    name: 'Health & Wellness',
    items: [
      'Yoga',
      'Meditation',
      'Fitness',
      'Mental Health',
      'Breathwork',
      'Pilates',
      'Wellness Retreat',
      'Nutrition',
      'Self Care',
      'Spa',
    ],
  },
  {
    name: 'Sports & Outdoor',
    items: [
      'Football',
      'Basketball',
      'Running',
      'Cycling',
      'Hiking',
      'Tennis',
      'Martial Arts',
      'Swimming',
      'Outdoor Adventure',
      'Esports',
    ],
  },
  {
    name: 'Fashion & Beauty',
    items: [
      'Runway',
      'Pop-up',
      'Beauty Class',
      'Makeup',
      'Skincare',
      'Streetwear',
      'Luxury',
      'Sustainable Fashion',
      'Thrift',
      'Hair',
    ],
  },
  {
    name: 'Education',
    items: [
      'Workshop',
      'Seminar',
      'Masterclass',
      'Bootcamp',
      'Language',
      'Exam Prep',
      'Skill Training',
      'Study Group',
      'Science',
      'History',
    ],
  },
  {
    name: 'Community & Causes',
    items: [
      'Meetup',
      'Volunteering',
      'Fundraiser',
      'Charity',
      'Civic',
      'Family',
      'Parenting',
      'Social Impact',
      'Support Group',
    ],
  },
  {
    name: 'Religion & Spirituality',
    items: [
      'Church Service',
      'Prayer Meeting',
      'Bible Study',
      'Islamic Lecture',
      'Quran Study',
      'Dhikr Gathering',
      'Hindu Satsang',
      'Temple Program',
      'Buddhist Meditation',
      'Retreat',
      'Interfaith Event',
      'Youth Fellowship',
    ],
  },
  {
    name: 'Entertainment & Nightlife',
    items: [
      'Comedy',
      'Games',
      'Trivia',
      'Movie Night',
      'Party',
      'Club Night',
      'Afterparty',
      'Festival',
      'Concert',
      'Live Show',
    ],
  },
  {
    name: 'Travel & Lifestyle',
    items: [
      'City Tour',
      'Weekend Getaway',
      'Adventure Trip',
      'Lifestyle',
      'Personal Development',
      'Home & Living',
      'Pets',
      'Gardening',
      'Photography Walk',
      'Road Trip',
    ],
  },
] as const;

export type EventCategoryName = (typeof EVENT_CATEGORY_GROUPS)[number]['name'];
